#ifndef LUAU_TYPE_DATABASE_H
#define LUAU_TYPE_DATABASE_H

// Roblox API type database extracted from luau-lsp globalTypes.d.luau
// Source: https://github.com/JohnnyMorganz/luau-lsp

#include <vector>
#include <string>
#include <unordered_map>

struct RobloxMember {
    const char* name;
    const char* sig;
    const char* desc;
    int kind;  // 1=method, 2=signal, 4=property
};

static const std::vector<RobloxMember>& roblox_get_members(const std::string& p_class) {
    static const std::unordered_map<std::string, std::vector<RobloxMember>> kDB = {

    {"Instance", {
        {"Name",              "string",           "Node name shown in explorer", 4},
        {"Parent",            "Instance?",        "Parent container node", 4},
        {"ClassName",         "string",           "Exact Roblox class type", 4},
        {"Archivable",        "boolean",          "Save with the place", 4},
        {"ChildAdded",        "RBXScriptSignal",  "Fires when a child is inserted", 2},
        {"ChildRemoved",      "RBXScriptSignal",  "Fires when a child is removed", 2},
        {"DescendantAdded",   "RBXScriptSignal",  "Fires when any descendant added", 2},
        {"DescendantRemoving","RBXScriptSignal",  "Fires before descendant removed", 2},
        {"Destroying",        "RBXScriptSignal",  "Fires when about to be destroyed", 2},
        {"AncestryChanged",   "RBXScriptSignal",  "Fires when Parent changes", 2},
        {"AttributeChanged",  "RBXScriptSignal<string>", "Fires when attribute changes", 2},
        {"Clone",             "() -> Instance",   "Deep copy of this instance", 1},
        {"Destroy",           "() -> ()",         "Remove permanently from memory", 1},
        {"ClearAllChildren",  "() -> ()",         "Destroy all children", 1},
        {"FindFirstChild",    "(name: string, recursive: boolean?) -> Instance?", "Find child by name", 1},
        {"FindFirstChildOfClass","(className: string) -> Instance?", "Find first child of class", 1},
        {"FindFirstChildWhichIsA","(className: string, recursive: boolean?) -> Instance?", "Find child by inheritance", 1},
        {"FindFirstAncestor", "(name: string) -> Instance?",    "Search parent chain by name", 1},
        {"FindFirstAncestorOfClass","(className: string) -> Instance?", "Search parent chain by class", 1},
        {"FindFirstDescendant","(name: string) -> Instance?",   "Find first descendant by name", 1},
        {"GetChildren",       "() -> {Instance}", "Array of direct children", 1},
        {"GetDescendants",    "() -> {Instance}", "All descendants in tree", 1},
        {"GetFullName",       "() -> string",     "Full path from root", 1},
        {"IsA",               "(className: string) -> boolean", "Check class inheritance", 1},
        {"IsAncestorOf",      "(descendant: Instance) -> boolean", "Check if ancestor", 1},
        {"IsDescendantOf",    "(ancestor: Instance) -> boolean",   "Check if descendant", 1},
        {"WaitForChild",      "(name: string, timeOut: number?) -> Instance?", "Wait for child to load", 1},
        {"GetAttribute",      "(attribute: string) -> any",       "Read a custom attribute", 1},
        {"SetAttribute",      "(attribute: string, value: any) -> ()", "Write a custom attribute", 1},
        {"GetAttributes",     "() -> {[string]: any}",            "All custom attributes table", 1},
        {"AddTag",            "(tag: string) -> ()",              "Add a CollectionService tag", 1},
        {"RemoveTag",         "(tag: string) -> ()",              "Remove a CollectionService tag", 1},
        {"HasTag",            "(tag: string) -> boolean",         "Check if has tag", 1},
        {"GetTags",           "() -> {string}",                   "Get all tags on instance", 1},
    }},

    {"BasePart", {
        {"Anchored",          "boolean",          "Freeze in place, ignore gravity", 4},
        {"AssemblyAngularVelocity","Vector3",     "Angular velocity of assembly", 4},
        {"AssemblyCenterOfMass","Vector3",        "Center of mass of assembly", 4},
        {"AssemblyLinearVelocity","Vector3",      "Linear velocity of assembly", 4},
        {"AssemblyMass",      "number",           "Total mass of assembly", 4},
        {"AssemblyRootPart",  "BasePart",         "Root part of the assembly", 4},
        {"BackSurface",       "Enum.SurfaceType", "Back face surface type", 4},
        {"BottomSurface",     "Enum.SurfaceType", "Bottom face surface type", 4},
        {"BrickColor",        "BrickColor",       "Roblox named color preset", 4},
        {"CFrame",            "CFrame",           "Position and orientation matrix", 4},
        {"CanCollide",        "boolean",          "Solid physics collision", 4},
        {"CanQuery",          "boolean",          "Detectable by raycasts/overlaps", 4},
        {"CanTouch",          "boolean",          "Fires Touched/TouchEnded events", 4},
        {"CastShadow",        "boolean",          "Casts a dynamic shadow", 4},
        {"CenterOfMass",      "Vector3",          "Local center of mass offset", 4},
        {"CollisionGroup",    "string",           "Collision group name", 4},
        {"Color",             "Color3",           "RGB surface tint", 4},
        {"CustomPhysicalProperties","PhysicalProperties", "Override material physics", 4},
        {"EnableFluidForces", "boolean",          "Affected by aerodynamics", 4},
        {"FrontSurface",      "Enum.SurfaceType", "Front face surface type", 4},
        {"LeftSurface",       "Enum.SurfaceType", "Left face surface type", 4},
        {"LocalTransparencyModifier","number",    "Extra transparency modifier", 4},
        {"Locked",            "boolean",          "Lock from Studio editing", 4},
        {"Mass",              "number",           "Mass in kg (read-only)", 4},
        {"Massless",          "boolean",          "Remove mass from assembly", 4},
        {"Material",          "Enum.Material",    "Visual + physical material", 4},
        {"MaterialVariant",   "string",           "Custom material variant name", 4},
        {"Orientation",       "Vector3",          "XYZ rotation in degrees", 4},
        {"PivotOffset",       "CFrame",           "Pivot point CFrame offset", 4},
        {"Position",          "Vector3",          "World position in studs", 4},
        {"Reflectance",       "number",           "Surface reflectiveness 0-1", 4},
        {"RightSurface",      "Enum.SurfaceType", "Right face surface type", 4},
        {"RootPriority",      "number",           "Assembly root priority", 4},
        {"Rotation",          "Vector3",          "World rotation in degrees", 4},
        {"Size",              "Vector3",          "Bounding box size in studs", 4},
        {"TopSurface",        "Enum.SurfaceType", "Top face surface type", 4},
        {"Transparency",      "number",           "Opacity: 0=solid, 1=invisible", 4},
        {"Touched",           "RBXScriptSignal<BasePart>",  "Part starts touching another", 2},
        {"TouchEnded",        "RBXScriptSignal<BasePart>",  "Part stops touching another", 2},
        {"NetworkOwnerChanged","RBXScriptSignal", "Network ownership changed", 2},
        {"ApplyAngularImpulse","(impulse: Vector3) -> ()",  "Instant angular force", 1},
        {"ApplyImpulse",      "(impulse: Vector3) -> ()",   "Instant force at center of mass", 1},
        {"ApplyImpulseAtPosition","(impulse: Vector3, position: Vector3) -> ()", "Force at world point", 1},
        {"CanCollideWith",    "(part: BasePart) -> boolean","Check collision between parts", 1},
        {"GetConnectedParts", "(recursive: boolean?) -> {BasePart}", "Get physically joined parts", 1},
        {"GetMass",           "() -> number",     "Get part mass in kg", 1},
        {"GetNetworkOwner",   "() -> Player?",    "Current network owner", 1},
        {"GetNetworkOwnershipAuto","() -> boolean","Is ownership automatic", 1},
        {"GetTouchingParts",  "() -> {BasePart}", "Parts currently in contact", 1},
        {"GetVelocityAtPosition","(position: Vector3) -> Vector3", "Velocity at world point", 1},
        {"IntersectAsync",    "(parts: {Instance}) -> Instance", "Boolean intersect CSG", 1},
        {"IsGrounded",        "() -> boolean",    "Assembly touching ground", 1},
        {"Resize",            "(normalId: Enum.NormalId, delta: number) -> boolean", "Resize in direction", 1},
        {"SetNetworkOwner",   "(playerInstance: Player?) -> ()", "Set network owner", 1},
        {"SetNetworkOwnershipAuto","() -> ()",    "Enable auto network ownership", 1},
        {"SubtractAsync",     "(parts: {BasePart}) -> Instance", "Boolean subtract CSG", 1},
        {"UnionAsync",        "(parts: {BasePart}) -> Instance", "Boolean union CSG", 1},
    }},

    {"Humanoid", {
        {"AutoJumpEnabled",   "boolean",          "Auto-jump on mobile/gamepad", 4},
        {"AutoRotate",        "boolean",          "Face movement direction automatically", 4},
        {"AutomaticScalingEnabled","boolean",     "Scale to HumanoidDescription", 4},
        {"BreakJointsOnDeath","boolean",          "Detach limbs when health hits 0", 4},
        {"CameraOffset",      "Vector3",          "Camera position offset from head", 4},
        {"DisplayName",       "string",           "Name displayed above character", 4},
        {"DisplayDistanceType","Enum.HumanoidDisplayDistanceType", "Name/health display mode", 4},
        {"EvaluateStateMachine","boolean",        "Enable automatic state transitions", 4},
        {"FloorMaterial",     "Enum.Material",    "Material currently walking on", 4},
        {"Health",            "number",           "Current health points", 4},
        {"HealthDisplayDistance","number",        "Distance to show health bar", 4},
        {"HipHeight",         "number",           "Hip height above floor in studs", 4},
        {"Jump",              "boolean",          "Set true to make character jump", 4},
        {"JumpHeight",        "number",           "Jump height in studs (JumpHeight mode)", 4},
        {"JumpPower",         "number",           "Jump power (JumpPower mode)", 4},
        {"MaxHealth",         "number",           "Maximum health points", 4},
        {"MaxSlopeAngle",     "number",           "Steepest walkable slope in degrees", 4},
        {"MoveDirection",     "Vector3",          "Current normalized move direction", 4},
        {"NameDisplayDistance","number",          "Distance to show name label", 4},
        {"PlatformStand",     "boolean",          "Enable platform standing state", 4},
        {"RequiresNeck",      "boolean",          "Die if neck Motor6D breaks", 4},
        {"RigType",           "Enum.HumanoidRigType", "R6 or R15 rig", 4},
        {"RootPart",          "BasePart?",        "HumanoidRootPart reference", 4},
        {"Sit",               "boolean",          "Force sitting state", 4},
        {"TargetPoint",       "Vector3",          "World-space aim point", 4},
        {"UseJumpPower",      "boolean",          "Use JumpPower instead of JumpHeight", 4},
        {"WalkSpeed",         "number",           "Movement speed studs/sec (default 16)", 4},
        {"WalkToPart",        "BasePart?",        "Part to walk toward", 4},
        {"WalkToPoint",       "Vector3",          "World position to walk toward", 4},
        {"Died",              "RBXScriptSignal",  "Fires when Health reaches 0", 2},
        {"HealthChanged",     "RBXScriptSignal<number>", "Fires when health value changes", 2},
        {"Jumping",           "RBXScriptSignal<boolean>","Fires on jump start/land", 2},
        {"Running",           "RBXScriptSignal<number>", "Fires with current walk speed", 2},
        {"Climbing",          "RBXScriptSignal<number>", "Fires while climbing", 2},
        {"Swimming",          "RBXScriptSignal<number>", "Fires while swimming", 2},
        {"FallingDown",       "RBXScriptSignal<boolean>","Fires when falling over", 2},
        {"FreeFalling",       "RBXScriptSignal<boolean>","Fires while in free fall", 2},
        {"GettingUp",         "RBXScriptSignal<boolean>","Fires when rising from fall", 2},
        {"MoveToFinished",    "RBXScriptSignal<boolean>","Fires when MoveTo() completes", 2},
        {"Seated",            "RBXScriptSignal<boolean, Seat>", "Fires on sit/unsit", 2},
        {"StateChanged",      "RBXScriptSignal<Enum.HumanoidStateType, Enum.HumanoidStateType>", "State transition occurred", 2},
        {"Touched",           "RBXScriptSignal<BasePart, BasePart>", "Humanoid touches a part", 2},
        {"TakeDamage",        "(amount: number) -> ()",  "Reduce health, respects ForceField", 1},
        {"Move",              "(direction: Vector3, relativeToCamera: boolean?) -> ()", "Force movement direction", 1},
        {"MoveTo",            "(location: Vector3, part: BasePart?) -> ()", "Walk to target", 1},
        {"ChangeState",       "(state: Enum.HumanoidStateType?) -> ()", "Force state change", 1},
        {"GetState",          "() -> Enum.HumanoidStateType", "Current state type", 1},
        {"GetStateEnabled",   "(state: Enum.HumanoidStateType) -> boolean", "Check if state enabled", 1},
        {"SetStateEnabled",   "(state: Enum.HumanoidStateType, enabled: boolean) -> ()", "Enable/disable state", 1},
        {"GetMoveVelocity",   "() -> Vector3",    "Current movement velocity", 1},
        {"GetAccessories",    "() -> {Accessory}","All equipped accessories", 1},
        {"EquipTool",         "(tool: Tool) -> ()", "Equip a tool", 1},
        {"UnequipTools",      "() -> ()",          "Remove all equipped tools", 1},
        {"RemoveAccessories", "() -> ()",          "Remove all accessories", 1},
        {"LoadAnimation",     "(animation: Animation) -> AnimationTrack", "Load animation for playback", 1},
        {"BuildRigFromAttachments","() -> ()",     "Build rig from Attachment nodes", 1},
        {"AddAccessory",      "(accessory: Accessory) -> ()", "Attach an accessory", 1},
        {"GetAppliedDescription","() -> HumanoidDescription", "Current avatar description", 1},
        {"ApplyDescriptionAsync","(description: HumanoidDescription) -> ()", "Apply avatar description", 1},
    }},

    {"Player", {
        {"AccountAge",        "number",           "Account age in days", 4},
        {"AutoJumpEnabled",   "boolean",          "Auto-jump on mobile", 4},
        {"CameraMaxZoomDistance","number",        "Max camera zoom distance", 4},
        {"CameraMinZoomDistance","number",        "Min camera zoom distance", 4},
        {"CameraMode",        "Enum.CameraMode",  "Camera follow mode", 4},
        {"Character",         "Model?",           "The player's 3D character model", 4},
        {"CharacterAppearanceId","number",        "Avatar appearance asset ID", 4},
        {"DevCameraOcclusionMode","Enum.DevCameraOcclusionMode", "Camera occlusion behavior", 4},
        {"DevComputerMovementMode","Enum.DevComputerMovementMode", "PC movement control mode", 4},
        {"DevTouchMovementMode","Enum.DevTouchMovementMode", "Mobile movement control mode", 4},
        {"DevEnableMouseLock","boolean",          "Allow mouse lock toggle", 4},
        {"DisplayName",       "string",           "Display name from Roblox profile", 4},
        {"FollowUserId",       "number",          "UserId of followed player", 4},
        {"GameplayPaused",    "boolean",          "Whether gameplay is paused", 4},
        {"HasVerifiedBadge",  "boolean",          "Has Roblox verified badge", 4},
        {"LocaleId",          "string",           "Player locale (e.g. en-us)", 4},
        {"MembershipType",    "Enum.MembershipType", "Roblox Premium tier", 4},
        {"Name",              "string",           "Roblox username", 4},
        {"Neutral",           "boolean",          "Not assigned to any team", 4},
        {"RespawnLocation",   "SpawnLocation",    "Custom respawn SpawnLocation", 4},
        {"Team",              "Team?",            "Current team instance", 4},
        {"TeamColor",         "BrickColor",       "Team's brick color", 4},
        {"UserId",            "number",           "Unique Roblox UserId", 4},
        {"VREnabled",         "boolean",          "Using a VR headset", 4},
        {"CharacterAdded",    "RBXScriptSignal<Model>",  "Fires when character spawns", 2},
        {"CharacterRemoving", "RBXScriptSignal<Model>",  "Fires before character removed", 2},
        {"CharacterAppearanceLoaded","RBXScriptSignal<Model>","Fires when appearance loaded", 2},
        {"Chatted",           "RBXScriptSignal<string, Player?>", "Fires when player sends chat", 2},
        {"Idled",             "RBXScriptSignal<number>", "Fires after 1 minute idle", 2},
        {"OnTeleport",        "RBXScriptSignal<Enum.TeleportState, number, string>", "Teleport state change", 2},
        {"Kick",              "(message: string?) -> ()", "Disconnect player from game", 1},
        {"GetMouse",          "() -> Mouse",       "Get the player's Mouse object", 1},
        {"GetNetworkPing",    "() -> number",      "Network latency in milliseconds", 1},
        {"GetFriendStatus",   "(player: Player) -> Enum.FriendStatus", "Friendship status", 1},
        {"GetRankInGroupAsync","(groupId: number) -> number", "Group rank 0-255", 1},
        {"GetRoleInGroupAsync","(groupId: number) -> string", "Group role name string", 1},
        {"IsInGroupAsync",    "(groupId: number) -> boolean", "Check group membership", 1},
        {"IsFriendsWithAsync","(userId: number) -> boolean",  "Check if friends", 1},
        {"DistanceFromCharacter","(point: Vector3) -> number", "Distance from character", 1},
        {"HasAppearanceLoaded","() -> boolean",    "Check if appearance has loaded", 1},
        {"LoadCharacterAsync","() -> ()",          "Reload character", 1},
        {"GetJoinData",       "() -> table",       "Teleport and launch join data", 1},
        {"Move",              "(walkDirection: Vector3, relativeToCamera: boolean?) -> ()", "Force movement", 1},
        {"RequestStreamAroundAsync","(position: Vector3, timeOut: number?) -> ()", "Request streaming area", 1},
        {"GetUnder13",        "() -> boolean",     "Check if player is under 13", 1},
        {"IsVerified",        "() -> boolean",     "Check Roblox ID verified status", 1},
    }},

    {"Players", {
        {"BubbleChat",        "boolean",          "Enable chat bubbles above heads", 4},
        {"CharacterAutoLoads","boolean",          "Auto-load character on join", 4},
        {"ClassicChat",       "boolean",          "Enable classic chat box", 4},
        {"LocalPlayer",       "Player",           "The client's own Player object", 4},
        {"MaxPlayers",        "number",           "Server maximum player count", 4},
        {"RespawnTime",       "number",           "Seconds before character respawns", 4},
        {"PlayerAdded",       "RBXScriptSignal<Player>",  "Fires when a player joins", 2},
        {"PlayerRemoving",    "RBXScriptSignal<Player>",  "Fires when a player leaves", 2},
        {"PlayerMembershipChanged","RBXScriptSignal<Player>", "Fires on membership change", 2},
        {"GetPlayers",        "() -> {Player}",   "Array of all active players", 1},
        {"GetPlayerByUserId", "(userId: number) -> Player?", "Find player by UserId", 1},
        {"GetPlayerFromCharacter","(character: Model) -> Player?", "Get player from character model", 1},
        {"GetNameFromUserIdAsync","(userId: number) -> string", "Fetch username from UserId", 1},
        {"GetUserIdFromNameAsync","(userName: string) -> number", "Fetch UserId from username", 1},
        {"GetHumanoidDescriptionFromUserIdAsync","(userId: number) -> HumanoidDescription", "Fetch avatar description", 1},
        {"GetUserThumbnailAsync","(userId: number, thumbType: Enum, thumbSize: Enum) -> (string, boolean)", "Get profile thumbnail URL", 1},
        {"CreateHumanoidModelFromDescriptionAsync","(desc: HumanoidDescription, rigType: Enum) -> Model", "Build character model", 1},
        {"Chat",              "(message: string) -> ()", "Broadcast chat message (server)", 1},
        {"SetChatStyle",      "(style: Enum.ChatStyle?) -> ()", "Set chat display style", 1},
        {"BanAsync",          "(config: table) -> ()", "Ban player(s) from experience", 1},
        {"UnbanAsync",        "(config: table) -> ()", "Unban player(s)", 1},
    }},

    {"Workspace", {
        {"AirDensity",        "number",           "Air resistance coefficient", 4},
        {"AirTurbulenceIntensity","number",        "Wind turbulence strength", 4},
        {"AllowThirdPartySales","boolean",         "Allow third-party purchases", 4},
        {"CurrentCamera",     "Camera",           "Active rendering camera", 4},
        {"DistributedGameTime","number",          "Total game time elapsed in seconds", 4},
        {"FallenPartsDestroyHeight","number",     "Y height below which parts are destroyed", 4},
        {"GlobalWind",        "Vector3",          "Global wind force vector", 4},
        {"Gravity",           "number",           "World gravity m/s² (default 196.2)", 4},
        {"StreamingEnabled",  "boolean",          "Enable content streaming", 4},
        {"Terrain",           "Terrain",          "Voxel terrain service instance", 4},
        {"PersistentLoaded",  "RBXScriptSignal<Player>", "Fires when persistent data loads", 2},
        {"Raycast",           "(origin: Vector3, direction: Vector3, params: RaycastParams?) -> RaycastResult?", "Cast a physics ray", 1},
        {"GetPartsInPart",    "(part: BasePart, params: OverlapParams?) -> {BasePart}", "Parts overlapping a part", 1},
        {"GetPartsInBox",     "(cframe: CFrame, size: Vector3, params: OverlapParams?) -> {BasePart}", "Parts in box region", 1},
        {"GetPartsInRadius",  "(position: Vector3, radius: number, params: OverlapParams?) -> {BasePart}", "Parts in sphere", 1},
        {"GetServerTimeNow",  "() -> number",     "Server-synchronized timestamp", 1},
        {"GetNumAwakeParts",  "() -> number",     "Count of active physics parts", 1},
        {"GetRealPhysicsFPS", "() -> number",     "Actual physics simulation rate", 1},
        {"CalculateJumpHeight","(gravity: number, jumpPower: number) -> number", "Compute jump height", 1},
        {"CalculateJumpPower","(gravity: number, jumpHeight: number) -> number", "Compute jump power", 1},
        {"CalculateJumpDistance","(gravity: number, jumpPower: number, walkSpeed: number) -> number", "Compute jump distance", 1},
        {"JoinToOutsiders",   "(objects: {Instance}, jointType: Enum.JointCreationMode) -> ()", "Create external joints", 1},
        {"UnjoinFromOutsiders","(objects: {Instance}) -> ()", "Remove external joints", 1},
        {"ZoomToExtents",     "() -> ()",         "Fit camera to all parts (Studio)", 1},
        {"PGSIsEnabled",      "() -> boolean",    "Check PGS solver status", 1},
    }},

    {"Lighting", {
        {"Ambient",           "Color3",           "Ambient shadow tint color", 4},
        {"Brightness",        "number",           "Global light intensity multiplier", 4},
        {"ClockTime",         "number",           "Time of day 0-24 hours", 4},
        {"ColorShift_Bottom", "Color3",           "Tint shift for downward-facing surfaces", 4},
        {"ColorShift_Top",    "Color3",           "Tint shift for upward-facing surfaces", 4},
        {"EnvironmentDiffuseScale","number",      "Environment diffuse contribution 0-1", 4},
        {"EnvironmentSpecularScale","number",     "Environment specular contribution 0-1", 4},
        {"ExposureCompensation","number",         "Camera exposure adjustment EV", 4},
        {"FogColor",          "Color3",           "Atmospheric fog color", 4},
        {"FogEnd",            "number",           "Distance where fog is fully opaque", 4},
        {"FogStart",          "number",           "Distance where fog begins", 4},
        {"GeographicLatitude","number",           "Sun arc latitude in degrees", 4},
        {"GlobalShadows",     "boolean",          "Enable dynamic sun shadows", 4},
        {"LightingStyle",     "Enum.LightingStyle","Future vs Legacy lighting mode", 4},
        {"OutdoorAmbient",    "Color3",           "Outdoor ambient light color", 4},
        {"ShadowSoftness",    "number",           "Shadow edge softness 0-1", 4},
        {"Technology",        "Enum.Technology",  "Lighting engine (ShadowMap=3 default)", 4},
        {"TimeOfDay",         "string",           "Time string in HH:MM:SS format", 4},
        {"LightingChanged",   "RBXScriptSignal<boolean>", "Fires when any lighting property changes", 2},
        {"GetMinutesAfterMidnight","() -> number","Minutes elapsed since midnight", 1},
        {"SetMinutesAfterMidnight","(minutes: number) -> ()", "Set time by minutes since midnight", 1},
        {"GetSunDirection",   "() -> Vector3",    "Normalized sun direction vector", 1},
        {"GetMoonDirection",  "() -> Vector3",    "Normalized moon direction vector", 1},
        {"GetMoonPhase",      "() -> number",     "Moon phase 0-1", 1},
    }},

    {"RunService", {
        {"FrameNumber",       "number",           "Current render frame counter", 4},
        {"RunState",          "Enum.RunState",    "Current execution state", 4},
        {"Heartbeat",         "RBXScriptSignal<number>",  "Every frame after physics (dt)", 2},
        {"PostSimulation",    "RBXScriptSignal<number>",  "After physics simulation (dt)", 2},
        {"PreAnimation",      "RBXScriptSignal<number>",  "Before animation step (dt)", 2},
        {"PreRender",         "RBXScriptSignal<number>",  "Before frame render (dt)", 2},
        {"PreSimulation",     "RBXScriptSignal<number>",  "Before physics step (dt)", 2},
        {"RenderStepped",     "RBXScriptSignal<number>",  "Every frame before render (dt)", 2},
        {"Stepped",           "RBXScriptSignal<number, number>", "Every physics step (time, dt)", 2},
        {"BindToRenderStep",  "(name: string, priority: number, fn: (dt: number) -> ()) -> ()", "Bind to render pipeline", 1},
        {"UnbindFromRenderStep","(name: string) -> ()", "Remove render binding by name", 1},
        {"IsClient",          "() -> boolean",    "Executing on client side", 1},
        {"IsServer",          "() -> boolean",    "Executing on server side", 1},
        {"IsStudio",          "() -> boolean",    "Running inside Godot/Roblox Studio", 1},
        {"IsRunning",         "() -> boolean",    "Game is actively running", 1},
        {"IsEdit",            "() -> boolean",    "In edit mode (not running)", 1},
        {"IsRunMode",         "() -> boolean",    "In run mode", 1},
        {"GetRobloxVersion",  "() -> string",     "Engine version string", 1},
        {"GetTotalScriptPlusExecutionTime","() -> number", "Cumulative script time", 1},
        {"Pause",             "() -> ()",         "Pause game (Studio)", 1},
        {"Run",               "() -> ()",         "Start game (Studio)", 1},
        {"Stop",              "() -> ()",         "Stop game (Studio)", 1},
    }},

    {"Camera", {
        {"CFrame",            "CFrame",           "Camera world position and orientation", 4},
        {"CameraSubject",     "Humanoid | BasePart | nil", "Instance the camera follows", 4},
        {"CameraType",        "Enum.CameraType",  "Camera behavior mode", 4},
        {"DiagonalFieldOfView","number",          "Diagonal field of view in degrees", 4},
        {"FieldOfView",       "number",           "Vertical field of view in degrees", 4},
        {"FieldOfViewMode",   "Enum.FieldOfViewMode", "FOV measurement axis", 4},
        {"Focus",             "CFrame",           "Camera focus point CFrame", 4},
        {"HeadLocked",        "boolean",          "Lock to VR head position", 4},
        {"HeadScale",         "number",           "VR head scale factor", 4},
        {"MaxAxisFieldOfView","number",           "Maximum axis FOV in degrees", 4},
        {"NearPlaneZ",        "number",           "Near clipping plane distance", 4},
        {"ViewportSize",      "Vector2",          "Viewport dimensions in pixels", 4},
        {"FirstPersonTransition","RBXScriptSignal<boolean>", "Entering/leaving first-person", 2},
        {"InterpolationFinished","RBXScriptSignal",           "Camera interpolation complete", 2},
        {"GetPartsObscuringTarget","(castPoints: {Vector3}, ignoreList: {Instance}) -> {BasePart}", "Find parts blocking view", 1},
        {"GetRenderCFrame",   "() -> CFrame",     "Actual rendered camera CFrame", 1},
        {"GetRoll",           "() -> number",     "Camera roll angle in radians", 1},
        {"SetRoll",           "(rollAngle: number) -> ()", "Set camera roll angle", 1},
        {"ScreenPointToRay",  "(x: number, y: number, depth: number?) -> Ray", "Screen coords to world ray", 1},
        {"ViewportPointToRay","(x: number, y: number, depth: number?) -> Ray", "Viewport to world ray", 1},
        {"WorldToScreenPoint","(worldPoint: Vector3) -> (Vector3, boolean)", "World position to screen", 1},
        {"WorldToViewportPoint","(worldPoint: Vector3) -> (Vector3, boolean)", "World position to viewport", 1},
        {"Zoom",              "(distance: number) -> boolean", "Zoom camera by amount", 1},
    }},

    {"Model", {
        {"LevelOfDetail",     "Enum.ModelLevelOfDetail", "LOD rendering mode", 4},
        {"ModelStreamingMode","Enum.ModelStreamingMode",  "Content streaming behavior", 4},
        {"PrimaryPart",       "BasePart?",        "Pivot part for MoveTo/PivotTo", 4},
        {"WorldPivot",        "CFrame",           "World pivot CFrame", 4},
        {"GetBoundingBox",    "() -> (CFrame, Vector3)", "Bounding box CFrame and size", 1},
        {"GetExtentsSize",    "() -> Vector3",    "Size of the bounding box", 1},
        {"GetScale",          "() -> number",     "Current uniform scale factor", 1},
        {"MoveTo",            "(position: Vector3) -> ()", "Move PrimaryPart to position", 1},
        {"PivotTo",           "(cframe: CFrame) -> ()",    "Move by pivot CFrame", 1},
        {"GetPivot",          "() -> CFrame",     "Current world pivot CFrame", 1},
        {"ScaleTo",           "(newScaleFactor: number) -> ()", "Scale model uniformly", 1},
        {"TranslateBy",       "(delta: Vector3) -> ()",    "Translate without rotation", 1},
    }},

    {"Sound", {
        {"AudioContent",      "Content",          "Sound asset content reference", 4},
        {"IsLoaded",          "boolean",          "True if audio data is loaded", 4},
        {"IsPaused",          "boolean",          "True if currently paused", 4},
        {"IsPlaying",         "boolean",          "True if currently playing", 4},
        {"IsSpatial",         "boolean",          "True if 3D positional audio", 4},
        {"Looped",            "boolean",          "Loop when playback reaches end", 4},
        {"PlayOnRemove",      "boolean",          "Play once when instance removed", 4},
        {"PlaybackLoudness",  "number",           "Current output loudness 0-1000", 4},
        {"PlaybackSpeed",     "number",           "Speed multiplier (1 = normal)", 4},
        {"Playing",           "boolean",          "True/false to start/stop", 4},
        {"RollOffGain",       "number",           "Distance attenuation gain", 4},
        {"RollOffMaxDistance","number",           "Distance where sound is inaudible", 4},
        {"RollOffMinDistance","number",           "Distance where rolloff begins", 4},
        {"RollOffMode",       "Enum.RollOffMode", "Distance attenuation curve type", 4},
        {"SoundGroup",        "SoundGroup?",      "Group for volume mixing", 4},
        {"SoundId",           "ContentId",        "Asset ID of the audio file", 4},
        {"TimeLength",        "number",           "Total duration in seconds", 4},
        {"TimePosition",      "number",           "Current playback position in seconds", 4},
        {"Volume",            "number",           "Volume level 0-10 (default 0.5)", 4},
        {"DidLoop",           "RBXScriptSignal<string, number>", "Fires each time audio loops", 2},
        {"Ended",             "RBXScriptSignal<string>",         "Fires when playback ends", 2},
        {"Loaded",            "RBXScriptSignal<string>",         "Fires when audio data loads", 2},
        {"Paused",            "RBXScriptSignal<string>",         "Fires when paused", 2},
        {"Played",            "RBXScriptSignal<string>",         "Fires when playback starts", 2},
        {"Resumed",           "RBXScriptSignal<string>",         "Fires when resumed from pause", 2},
        {"Stopped",           "RBXScriptSignal<string>",         "Fires when stopped", 2},
        {"Play",              "() -> ()",         "Start playback from TimePosition", 1},
        {"Pause",             "() -> ()",         "Pause at current position", 1},
        {"Resume",            "() -> ()",         "Resume from paused position", 1},
        {"Stop",              "() -> ()",         "Stop and reset to beginning", 1},
    }},

    {"TweenService", {
        {"Create",   "(instance: Instance, tweenInfo: TweenInfo, propertyTable: table) -> Tween", "Create a property animation tween", 1},
        {"GetValue", "(alpha: number, easingStyle: Enum.EasingStyle, easingDirection: Enum.EasingDirection) -> number", "Get eased value for alpha", 1},
    }},

    {"UserInputService", {
        {"GamepadEnabled",    "boolean",          "A gamepad is connected", 4},
        {"GyroscopeEnabled",  "boolean",          "Gyroscope is available", 4},
        {"KeyboardEnabled",   "boolean",          "Physical keyboard connected", 4},
        {"MouseBehavior",     "Enum.MouseBehavior","Mouse lock mode", 4},
        {"MouseDeltaSensitivity","number",        "Mouse sensitivity multiplier", 4},
        {"MouseEnabled",      "boolean",          "Physical mouse is connected", 4},
        {"MouseIconEnabled",  "boolean",          "Show or hide mouse cursor", 4},
        {"OnScreenKeyboardVisible","boolean",     "Virtual keyboard is visible", 4},
        {"TouchEnabled",      "boolean",          "Touch screen is available", 4},
        {"VREnabled",         "boolean",          "VR headset is connected", 4},
        {"InputBegan",        "RBXScriptSignal<InputObject, boolean>",  "Any input press started", 2},
        {"InputChanged",      "RBXScriptSignal<InputObject, boolean>",  "Input state changed (mouse move)", 2},
        {"InputEnded",        "RBXScriptSignal<InputObject, boolean>",  "Any input press ended", 2},
        {"GamepadConnected",  "RBXScriptSignal<Enum.UserInputType>",    "Gamepad was connected", 2},
        {"GamepadDisconnected","RBXScriptSignal<Enum.UserInputType>",   "Gamepad was disconnected", 2},
        {"JumpRequest",       "RBXScriptSignal",                        "Mobile jump button pressed", 2},
        {"TextBoxFocused",    "RBXScriptSignal<TextBox>",               "TextBox gained focus", 2},
        {"TextBoxFocusReleased","RBXScriptSignal<TextBox>",             "TextBox lost focus", 2},
        {"TouchStarted",      "RBXScriptSignal<InputObject, boolean>",  "Touch began", 2},
        {"TouchEnded",        "RBXScriptSignal<InputObject, boolean>",  "Touch ended", 2},
        {"TouchMoved",        "RBXScriptSignal<InputObject, boolean>",  "Touch moved", 2},
        {"TouchTap",          "RBXScriptSignal<{Vector2}, boolean>",    "Single tap gesture", 2},
        {"TouchPinch",        "RBXScriptSignal",                        "Pinch zoom gesture", 2},
        {"TouchSwipe",        "RBXScriptSignal<Enum.SwipeDirection, number, boolean>", "Swipe gesture", 2},
        {"WindowFocused",     "RBXScriptSignal",                        "Game window gained focus", 2},
        {"WindowFocusReleased","RBXScriptSignal",                       "Game window lost focus", 2},
        {"IsKeyDown",         "(keyCode: Enum.KeyCode) -> boolean",     "Check if a key is held down", 1},
        {"IsMouseButtonPressed","(mouseButton: Enum.UserInputType) -> boolean", "Check mouse button state", 1},
        {"GetMouseDelta",     "() -> Vector2",    "Mouse movement delta this frame", 1},
        {"GetMouseLocation",  "() -> Vector2",    "Current mouse screen position", 1},
        {"GetKeysPressed",    "() -> {InputObject}", "All currently pressed keys", 1},
        {"GetMouseButtonsPressed","() -> {InputObject}", "Pressed mouse buttons", 1},
        {"GetConnectedGamepads","() -> {Enum.UserInputType}", "List of connected gamepads", 1},
        {"GetGamepadState",   "(gamepadNum: Enum.UserInputType) -> {InputObject}", "All button states", 1},
        {"GetFocusedTextBox", "() -> TextBox",    "Currently focused TextBox or nil", 1},
        {"GetLastInputType",  "() -> Enum.UserInputType", "Type of last input device used", 1},
        {"GetStringForKeyCode","(keyCode: Enum.KeyCode) -> string", "Localized key display name", 1},
        {"IsGamepadButtonDown","(gamepadNum: Enum.UserInputType, keyCode: Enum.KeyCode) -> boolean", "Check gamepad button state", 1},
        {"RecenterUserHeadCFrame","() -> ()",     "Re-center VR head position", 1},
        {"GamepadSupports",   "(gamepadNum: Enum.UserInputType, keyCode: Enum.KeyCode) -> boolean", "Check gamepad button support", 1},
    }},

    {"RemoteEvent", {
        {"OnServerEvent",  "RBXScriptSignal<Player, ...>", "Server-side: receives :FireServer() calls", 2},
        {"OnClientEvent",  "RBXScriptSignal<...>",         "Client-side: receives :FireClient() calls", 2},
        {"FireServer",     "(...: any) -> ()",             "Send data from client to server", 1},
        {"FireClient",     "(player: Player, ...: any) -> ()", "Send data to one specific client", 1},
        {"FireAllClients", "(...: any) -> ()",             "Broadcast data to all clients", 1},
    }},

    {"RemoteFunction", {
        {"OnServerInvoke",  "function",                    "Handler called when client invokes", 4},
        {"OnClientInvoke",  "function",                    "Handler called when server invokes", 4},
        {"InvokeServer",    "(...: any) -> ...any",        "Call server handler and wait for return", 1},
        {"InvokeClient",    "(player: Player, ...: any) -> ...any", "Call client handler and wait", 1},
    }},

    {"BindableEvent", {
        {"Event",  "RBXScriptSignal",  "Connect to listen for :Fire() calls", 2},
        {"Fire",   "(...: any) -> ()", "Fire to all same-side listeners", 1},
    }},

    {"BindableFunction", {
        {"OnInvoke", "function",            "Handler assigned and called by :Invoke()", 4},
        {"Invoke",   "(...: any) -> ...any","Synchronously call OnInvoke handler", 1},
    }},

    {"StarterPlayer", {
        {"AllowCustomAnimations","boolean",        "Allow custom R15 avatar animations", 4},
        {"AutoJumpEnabled",  "boolean",            "Auto-jump on mobile and gamepad", 4},
        {"CameraMaxZoomDistance","number",         "Maximum camera zoom distance", 4},
        {"CameraMinZoomDistance","number",         "Minimum camera zoom distance", 4},
        {"CameraMode",       "Enum.CameraMode",    "Default camera follow mode", 4},
        {"CharacterBreakJointsOnDeath","boolean",  "Ragdoll on death", 4},
        {"CharacterJumpHeight","number",           "Default jump height in studs", 4},
        {"CharacterJumpPower","number",            "Default jump power", 4},
        {"CharacterMaxSlopeAngle","number",        "Steepest walkable slope degrees", 4},
        {"CharacterUseJumpPower","boolean",        "Use JumpPower mode", 4},
        {"CharacterWalkSpeed","number",            "Default walk speed (default 16)", 4},
        {"DevCameraOcclusionMode","Enum.DevCameraOcclusionMode", "Camera occlusion behavior", 4},
        {"DevComputerCameraMovementMode","Enum.DevComputerCameraMovementMode", "PC camera mode", 4},
        {"DevComputerMovementMode","Enum.DevComputerMovementMode", "PC movement mode", 4},
        {"DevTouchCameraMovementMode","Enum.DevTouchCameraMovementMode", "Mobile camera mode", 4},
        {"DevTouchMovementMode","Enum.DevTouchMovementMode", "Mobile movement mode", 4},
        {"EnableMouseLockOption","boolean",        "Allow shift-lock mouse toggle", 4},
        {"HealthDisplayDistance","number",         "Distance to show health bar", 4},
        {"LoadCharacterAppearance","boolean",      "Load player avatar appearance", 4},
        {"NameDisplayDistance","number",           "Distance to show name label", 4},
        {"UserEmotesEnabled","boolean",            "Allow user emote playback", 4},
    }},

    {"DataModel", {
        {"Workspace",          "Workspace",        "Physical game world", 4},
        {"Players",            "Players",          "Players service", 4},
        {"Lighting",           "Lighting",         "Lighting and sky service", 4},
        {"ReplicatedStorage",  "ReplicatedStorage","Shared client and server storage", 4},
        {"ReplicatedFirst",    "ReplicatedFirst",  "Loads before everything else", 4},
        {"ServerScriptService","ServerScriptService", "Secure server-side scripts", 4},
        {"ServerStorage",      "ServerStorage",    "Server-only storage", 4},
        {"StarterGui",         "StarterGui",       "Default GUIs cloned to players", 4},
        {"StarterPlayer",      "StarterPlayer",    "Player spawn configuration", 4},
        {"StarterPack",        "StarterPack",      "Tools cloned to player backpack", 4},
        {"Teams",              "Teams",            "Team management service", 4},
        {"SoundService",       "SoundService",     "Global audio control service", 4},
        {"TextChatService",    "TextChatService",  "In-game chat system", 4},
        {"RunService",         "RunService",       "Per-frame signals service", 4},
        {"GetService",         "(className: string) -> Instance",  "Get or create a service", 1},
        {"FindService",        "(className: string) -> Instance?", "Find existing service", 1},
        {"IsLoaded",           "() -> boolean",    "True when all content is loaded", 1},
    }},

    {"Script", {
        {"Disabled", "boolean", "Prevent script from executing", 4},
        {"Source",   "string",  "Luau source code text", 4},
        {"Name",     "string",  "Script node name", 4},
    }},

    {"LocalScript", {
        {"Disabled", "boolean", "Prevent script from executing", 4},
        {"Source",   "string",  "Luau source code text", 4},
        {"Name",     "string",  "Script node name", 4},
    }},

    {"ModuleScript", {
        {"Source",   "string",  "Luau module source code", 4},
        {"Name",     "string",  "Module node name", 4},
    }},

    {"Tween", {
        {"TweenInfo",      "TweenInfo",          "Configuration used to create this tween", 4},
        {"PlaybackState",  "Enum.PlaybackState", "Current playback state", 4},
        {"Completed",      "RBXScriptSignal<Enum.PlaybackState>", "Fires when tween finishes", 2},
        {"Play",           "() -> ()",           "Start or resume the tween", 1},
        {"Pause",          "() -> ()",           "Pause at current state", 1},
        {"Cancel",         "() -> ()",           "Cancel and reset to initial values", 1},
    }},

    {"AnimationTrack", {
        {"Animation",      "Animation",          "Source animation asset", 4},
        {"IsPlaying",      "boolean",            "True if track is active", 4},
        {"Length",         "number",             "Animation duration in seconds", 4},
        {"Looped",         "boolean",            "Loop on completion", 4},
        {"Priority",       "Enum.AnimationPriority", "Blend priority level", 4},
        {"Speed",          "number",             "Playback speed multiplier", 4},
        {"TimePosition",   "number",             "Current position in seconds", 4},
        {"WeightCurrent",  "number",             "Current blend weight", 4},
        {"WeightTarget",   "number",             "Target blend weight", 4},
        {"DidLoop",        "RBXScriptSignal",    "Fires each loop cycle", 2},
        {"Ended",          "RBXScriptSignal",    "Fires when stopped or completed", 2},
        {"KeyframeReached","RBXScriptSignal<string>", "Fires at a named keyframe marker", 2},
        {"Play",           "(fadeTime: number?, weight: number?, speed: number?) -> ()", "Start playing", 1},
        {"Stop",           "(fadeTime: number?) -> ()",   "Stop with optional fade", 1},
        {"AdjustSpeed",    "(speed: number) -> ()",       "Change playback speed", 1},
        {"AdjustWeight",   "(weight: number, fadeTime: number?) -> ()", "Change blend weight", 1},
        {"GetTimeOfKeyframe","(keyframeName: string) -> number", "Time position of named keyframe", 1},
    }},

    {"ProximityPrompt", {
        {"ActionText",     "string",             "Interaction action label", 4},
        {"Enabled",        "boolean",            "Prompt is active and visible", 4},
        {"GamepadKeyCode", "Enum.KeyCode",        "Gamepad button to activate", 4},
        {"HoldDuration",   "number",             "Seconds to hold before triggering", 4},
        {"KeyboardKeyCode","Enum.KeyCode",        "Keyboard key to activate", 4},
        {"MaxActivationDistance","number",        "Maximum interaction distance", 4},
        {"ObjectText",     "string",             "Object name shown on prompt", 4},
        {"RequiresLineOfSight","boolean",         "Must have clear line of sight", 4},
        {"Triggered",      "RBXScriptSignal<Player>",  "Fires when player activates", 2},
        {"TriggerEnded",   "RBXScriptSignal<Player>",  "Fires when activation ends", 2},
        {"PromptShown",    "RBXScriptSignal<Player, Enum.ProximityPromptInputType>", "Prompt displayed to player", 2},
        {"PromptHidden",   "RBXScriptSignal<Player>",  "Prompt hidden from player", 2},
    }},

    }; // end kDB

    static const std::vector<RobloxMember> kEmpty;
    std::string key = p_class;
    if (key == "game") key = "DataModel";
    auto it = kDB.find(key);
    return (it != kDB.end()) ? it->second : kEmpty;
}

#endif // LUAU_TYPE_DATABASE_H
